site_name: 'Above Property Security Policies, Standards, and Procedures'
site_description: 'Above Property Security Policies, Standards, and Procedures'
site_url: 'https://compliance.aboveproperty.com/'
site_author: 'Above Property Systems, LLC.'

theme:
  name: material
  theme_dir: 'custom_theme'
  include_sidebar: false
  palette:
    primary: 'indigo'
    accent: ''
  favicon: 'assets/images/favicon.ico'
  logo: 'assets/images/aps_logo.png'

# Enable custom.css
extra_css:
  - 'assets/css/custom.css'

# Turn off "Made with Material for MkDocs"
extra:
  generator: false

plugins:
  - search
  - with-pdf:
      cover_subtitle: Security Policies, Standards, and Procedures
      output_path: pdf/Above_Property_Information_Security_Policy.pdf

markdown_extensions:
  - smarty
  - toc:
      permalink: true
  - sane_lists
  - admonition
  - codehilite:
      guess_lang: false
nav:
- 'Home': 'index.md'
- 'Security Program Overview': 'program.md'
- 'Corporate Governance': 'corp-gov.md'
- 'Policy Management': 'policy-mgmt.md'
- 'Security Architecture and Operating Model': 'model.md'
- 'Roles, Responsibilities and Training': 'rar.md'
- 'Risk Management and Risk Assessment Process': 'risk-mgmt.md'
- 'Compliance Audits and External Communications': 'compliance-audit.md'
- 'System Audits, Monitoring and Assessments': 'system-audit.md'
- 'HR and Personnel Security': 'hr.md'
- 'Access': 'access.md'
- 'Facility Access and Physical Security': 'facility.md'
- 'Asset Inventory Management': 'asset-mgmt.md'
- 'Data Management': 'data-mgmt.md'
- 'Data Protection': 'data-protection.md'
- 'Secure Software Development and Product Security': 'sdlc.md'
- 'Configuration and Change Management': 'ccm.md'
- 'Threat Detection and Prevention': 'threat.md'
- 'Vulnerability Management': 'vuln-mgmt.md'
- 'Mobile Device Security and Media Management': 'mdm.md'
- 'Business Continuity and Disaster Recovery': 'bcdr.md'
- 'Incident Response': 'ir.md'
- 'Breach Investigation and Notification': 'breach.md'
- 'Third Party Security and Vendor Risk Management': 'vendor.md'
- 'Privacy Practice and Consent': 'privacy.md'
- 'Addendum and References': 'ref.md'
- 'Appendix A. Employee Handbook': 'employee-handbook.md'
- 'Appendix B. Approved Software': 'approved-software.md'
- 'Appendix C. Approved Vendors': 'approved-vendors.md'
- 'Appendix D. Key Definitions': 'definitions.md'
- 'Appendix E. Privacy Policy': 'privacy-policy.md'
- 'Appendix F. Cookie Policy': 'cookie-policy.md'
- 'Appendix G. GDPR Data Processing Agreement': 'gdpr-dpa.md'
- 'Appendix H. NIST requirements mapping': 'nist-mapping.md'
- 'Appendix I. PCI DSS Controls Mapping': 'pci-dss-3-mapping.md'
- 'Appendix J. Current PCI DSS AOC': 'pci-certification.md'
- 'Appendix K. Complete PDF of this site': 'pdf.md'

