name: Compliance website workflow
on:
  push:
    branches:
      - main
env:
  AWS_REGION: "us-east-1"
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  COMPLIANCE_BUCKET: ${{ secrets.COMPLIANCE_BUCKET }}
  CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}

permissions:
  # Use OIDC instead of long-lived credentials:
  # https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services
  id-token: write   # This is required for requesting the JWT from AWS
  contents: read    # This is required for actions/checkout

jobs:
  BuildAndDeploySite:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
      - name: set up node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install policy builder
        run: npm install -g @jupiterone/jupiter-policy-builder
      - name: set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: set up mkdocs
        run: pip install mkdocs-with-pdf mkdocs mkdocs-material mkdocs-material-extensions pymdown-extensions
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_ROLE }}
          aws-region: ${{ env.AWS_REGION }}
      # Upload a file to AWS s3
      - name:  Build and deploy the site
        run: |
          ./build.sh
